### ISSUE TITLE
JmxMonitorRegistry race condition with RibbonClient

### ISSUE THREAD

**Issue by bstick12** [Netflix/feign#182]
If you run the following test - https://gist.github.com/bstick12/2a21ffd30b14ec68716f#file-ribbonclienttest

You will occasionally get the the following warning issued from servo.

The com.netflix.loadbalancer.LoadBalancerContext.initWithNiwsConfig(IClientConfig) registers the load balancer and the RibbonClient is recreating the LBClient on each request.

```
0:44:38.155 [pool-1-thread-2] WARN  c.n.servo.jmx.JmxMonitorRegistry - Unable to register Monitor:MonitorConfig{name=Client_github, tags=class=LBClient, policy=DefaultPublishingPolicy}
javax.management.InstanceNotFoundException: com.netflix.servo:name=github_LoadBalancerExecutionTimer,statistic=max,class=LBClient,type=GAUGE,id=Client_github,unit=MILLISECONDS
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.7.0_72]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427) ~[na:1.7.0_72]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415) ~[na:1.7.0_72]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546) ~[na:1.7.0_72]
	at com.netflix.servo.jmx.JmxMonitorRegistry.register(JmxMonitorRegistry.java:82) ~[servo-core-0.7.4.jar:na]
	at com.netflix.servo.jmx.JmxMonitorRegistry.register(JmxMonitorRegistry.java:106) ~[servo-core-0.7.4.jar:na]
	at com.netflix.servo.DefaultMonitorRegistry.register(DefaultMonitorRegistry.java:135) [servo-core-0.7.4.jar:na]
	at com.netflix.servo.monitor.Monitors.registerObject(Monitors.java:207) [servo-core-0.7.4.jar:na]
	at com.netflix.loadbalancer.LoadBalancerContext.initWithNiwsConfig(LoadBalancerContext.java:111) [ribbon-loadbalancer-2.0-RC5.jar:na]
	at com.netflix.loadbalancer.LoadBalancerContext.<init>(LoadBalancerContext.java:82) [ribbon-loadbalancer-2.0-RC5.jar:na]
	at com.netflix.loadbalancer.LoadBalancerExecutor.<init>(LoadBalancerExecutor.java:45) [ribbon-loadbalancer-2.0-RC5.jar:na]
	at com.netflix.client.AbstractLoadBalancerAwareClient.<init>(AbstractLoadBalancerAwareClient.java:54) [ribbon-loadbalancer-2.0-RC5.jar:na]
	at feign.ribbon.LBClient.<init>(LBClient.java:47) [feign-ribbon-7.2.0.jar:7.2.0]
	at feign.ribbon.RibbonClient.lbClient(RibbonClient.java:76) [feign-ribbon-7.2.0.jar:7.2.0]
	at feign.ribbon.RibbonClient.execute(RibbonClient.java:64) [feign-ribbon-7.2.0.jar:7.2.0]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:95) [feign-core-7.2.0.jar:7.2.0]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74) [feign-core-7.2.0.jar:7.2.0]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:101) [feign-core-7.2.0.jar:7.2.0]
	at com.brendan.atlassian.$Proxy6.users(Unknown Source) [na:na]
	at com.brendan.atlassian.RibbonClientTest$1.run(RibbonClientTest.java:56) [test-classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_72]
```

**Comment by adriancole** [comment]
do you know the ideal way we should behave wrt creating these instances? I
mean are we needlessly creating things, or should we be locking on
something?

**Comment by bstick12** [comment]
From what I've seen in the Ribbon libraries all the objects are cached within the ClientFactory. It does look like that creating the LBClient on each request isn't what the designers of the LoadBalancerContext super class had in mind due to the Monitor registration.

If you are happy enough with the approach to this and #183 I'll look at adding some tests

**Comment by adriancole** [comment]
made some notes, but looks like you are well on your way. thanks for the
help!

**Comment by adriancole** [comment]
I'm convinced that addressing the problem of `Monitors.registerObject()/DefaultMonitorRegistry.register()` by guards in Feign is the wrong solution. It distracts our codebase unnecessarily especially since servo is OSS and also there's a workaround to this problem.

The workaround is to write or chose another `com.netflix.servo.MonitorRegistry` which doesn't have a race condition and configure that via the system property `com.netflix.servo.DefaultMonitorRegistry.registryClass`

I will open a ticket in servo to address the race condition in servo itself. We or others can implement that with a loading cache there.

@bstick12 I sincerely appreciate your effort, and hope this doesn't disappoint you. My hope is that if we chase the issue upstream, we can still resolve the problem you raised, but for everyone, not just feign.

**Comment by bstick12** [comment]
@adriancole I've not problem with that and to address the problem locally that is the solution I have gone with.

But I would like to look at allow the caching of the LBClients would you be averse to a pull request that changed the visibility on the LBClient to public and the RibbonClient#lbClient to protected?

**Comment by adriancole** [comment]
Actually, I really like the idea of allowing RibbonClient to have a LBClientFactory. Particularly, this gets around the problem of static factories which I don't like anyway :) Let's add that as a separate feature and note it in the changelog.

ex.
```java
public interface LBClientFactory {
  LBClient create(String clientName);

  /** Uses {@link ClientFactory static factories from ribbon} to create an LBClient. */ 
  public static final class Default implements LBClientFactory {
      @Override
       public LBClient create(String clientName) {
          IClientConfig config = ClientFactory.getNamedConfig(clientName);
          ILoadBalancer lb = ClientFactory.getNamedLoadBalancer(clientName);
          return new LBClient(lb, config);
       }
  }
}
```

**Comment by adriancole** [comment]
opened https://github.com/Netflix/servo/pull/306 to fix the race
