### ISSUE TITLE
javax.management.InstanceNotFoundException in multi threaded environment

### ISSUE THREAD

**Issue by beku8** [Netflix/feign#226]
I'm using feign clients in multi threaded event loop(rxjava + spring cloud), which calls the same client multiple times concurrently from different threads, which results(occasionally)
```
javax.management.InstanceNotFoundException: com.netflix.servo:name=core_LoadBalancerExecutionTimer,statistic=totalTime,class=RibbonLoadBalancer,type=GAUGE,id=Client_core,unit=MILLISECONDS
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546)
	at com.netflix.servo.jmx.JmxMonitorRegistry.register(JmxMonitorRegistry.java:82)
	at com.netflix.servo.jmx.JmxMonitorRegistry.register(JmxMonitorRegistry.java:106)
	at com.netflix.servo.DefaultMonitorRegistry.register(DefaultMonitorRegistry.java:135)
	at com.netflix.servo.monitor.Monitors.registerObject(Monitors.java:207)
	at com.netflix.loadbalancer.LoadBalancerContext.initWithNiwsConfig(LoadBalancerContext.java:103)
	at com.netflix.loadbalancer.LoadBalancerContext.<init>(LoadBalancerContext.java:74)
	at com.netflix.client.AbstractLoadBalancerAwareClient.<init>(AbstractLoadBalancerAwareClient.java:50)
	at org.springframework.cloud.netflix.feign.ribbon.RibbonLoadBalancer.<init>(RibbonLoadBalancer.java:53)
	at org.springframework.cloud.netflix.feign.ribbon.FeignRibbonClient.getClient(FeignRibbonClient.java:88)
	at org.springframework.cloud.netflix.feign.ribbon.FeignRibbonClient.execute(FeignRibbonClient.java:66)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:117)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:96)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:92)
	at com.sun.proxy.$Proxy115.findByCriteria(Unknown Source)
	at com.fm.nd.service.generate.ItemPriceServiceImpl$$EPBhbNaK.findItemPrice(ItemPriceServiceImpl.java:40)
	at com.fm.nd.service.generate.ItemPriceServiceImpl$$DPBhbNaK.findItemPrice(Unknown Source)
	at com.fm.nd.service.generate.ItemPriceServiceImpl.findItemPrice(ItemPriceServiceImpl.java)
	at com.fm.nd.service.generate.RatioItemGenerator$$EPBhfuXg.findItemPrice(RatioItemGenerator.java:43)
	at com.fm.nd.service.generate.RatioItemGenerator$$DPBhfuXg.findItemPrice(Unknown Source)
	at com.fm.nd.service.generate.RatioItemGenerator.findItemPrice(RatioItemGenerator.java)
	at com.fm.nd.service.generate.ServiceItemDtoGenerator.fillServiceItemPrice(ServiceItemDtoGenerator.java:19)
	at com.fm.nd.service.generate.RatioItemGenerator.fillServiceItemPrice(RatioItemGenerator.java)
	at com.fm.nd.service.generate.FormulaServiceImpl$$EPBhd1p2.lambda$0(FormulaServiceImpl.java:122)
	at com.fm.nd.service.generate.FormulaServiceImpl$$EPBhd1p2$$Lambda$628/30937552.call(Unknown Source)
	at rx.Observable.unsafeSubscribe(Observable.java:7495)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.fm.nd.common.rx.SchedulersHook.lambda$0(SchedulersHook.java:18)
	at com.fm.nd.common.rx.SchedulersHook$$Lambda$629/17129870.call(Unknown Source)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I've seen this similar issue https://github.com/Netflix/feign/issues/182. Is there anything I can do?

**Comment by adriancole** [comment]
so you are using latest feign and getting this?

**Comment by beku8** [comment]
Version is 7.1.0

**Comment by adriancole** [comment]
Pretty sure the fix would have been later than 7.x. want? Can you try 8.2?

**Comment by adriancole** [comment]
Quick look is the change went out in 7.3.0. 7.4.0 is the last version in 7.x

Hope this helps

**Comment by beku8** [comment]
Ok thanks @adriancole. I will check it out.

**Comment by beku8** [comment]
Yep the version update fixed the issue

**Comment by anjanb** [comment]
Hi @adriancole ,

  What was the fix about ? Can you share some details ?
Thanks very much,
