### ISSUE TITLE
@Param conflict with Spring 

### ISSUE THREAD

**Issue by VFT** [Netflix/feign#296]
Spring version：4.1.2.RELEASE
feign version：8.11.0

the error info trigger when i managed Feign Builder instance by the spring container：
```java
Caused by: java.lang.IllegalStateException: Method has too many Body parameters: public abstract cloudnil.bamboo.client.model.Service cloudnil.bamboo.client.Bamboo.bindService(java.lang.String,cloudnil.bamboo.client.model.Service)
	at feign.Util.checkState(Util.java:106)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:78)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:47)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:144)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:54)
	at feign.Feign$Builder.target(Feign.java:254)
	at feign.Feign$Builder.target(Feign.java:250)
	at cloudnil.bamboo.client.BambooClient.getInstance(BambooClient.java:37)
	at com.justep.framework.core.service.impl.MesosServiceImpl.<init>(MesosServiceImpl.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 42 more
```
How to do this?

**Comment by adriancole** [comment]
can you post a link to the source of BambooClient? We at least have a bug
as the error message should say which method was in error.

**Comment by VFT** [comment]
yes,post link to the source of BambooClient normally without spring.

such as this:
```java
public static void main(String[] args) {
		Bamboo b=BambooClient.getInstance("http://192.168.2.91:8000");
		Service service=new Service();
		service.setId("/2553e9c8-820f-11e5-9a33-8c89a50daed8/meikj2grev");
		service.setAcl("hdr(host) -i tiger2.justpaas.com");
		b.bindService("/2553e9c8-820f-11e5-9a33-8c89a50daed8/meikj2grev",service);
	}
```
and the source code of BambooClient:
```java
public class BambooClient {
	static class BambooHeadersInterceptor implements RequestInterceptor {
		@Override
		public void apply(RequestTemplate template) {
			template.header("Accept", "application/json");
			template.header("Content-Type", "application/json");
		}
	}

	static class BambooErrorDecoder implements ErrorDecoder {
		@Override
		public Exception decode(String methodKey, Response response) {
			return new BambooException(response.status(), response.reason());
		}
	}

	public static Bamboo getInstance(String endpoint) {
		JacksonDecoder decoder = ModelUtils.decoder();
		JacksonEncoder encoder = ModelUtils.encoder();
		return Feign.builder().encoder(encoder).decoder(decoder).errorDecoder(new BambooErrorDecoder())
				.requestInterceptor(new BambooHeadersInterceptor()).target(Bamboo.class, endpoint);
	}
}
```

source code of Bamboo.bindService():
```java
	@RequestLine("PUT /api/services/{id}")
	Service bindService(@Param("id")String id,Service service);
```

**Comment by adriancole** [comment]
So to be clear, bindService is the method that works on its own, but throws
an exception when packaged with other things?

**Comment by VFT** [comment]
yes

**Comment by adriancole** [comment]
I've seen problems when types are package protected and accessed from
different jars (class loaders). Might be unrelated, but is are your types
package protected and in different jars/class loaders?

**Comment by VFT** [comment]
The problem is solved.import different version of feign,I was too careless
