### ISSUE TITLE
Spring MVC's /path/{id:.+} notation doesn't work

### ISSUE THREAD

**Issue by bsideup** [Netflix/feign#351]
When regexp is being used in path parameter configuration Feign fails with

```
Caused by: java.lang.IllegalStateException: Body parameters cannot be used with form parameters.
	at feign.Util.checkState(Util.java:117)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:109)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:61)
```

**Comment by adriancole** [comment]
Version 8.15.1 I presume?

I'll take a look before tomorrow unless you get to it first.

I suspect this would break with default contract, too? `@RequestLine("GET
/path/{id:.+}")`
