### ISSUE TITLE
Feign Hystrix fallback can't access method in packaged interface 

### ISSUE THREAD

**Issue by liuzhengyang** [Netflix/feign#353]
If apiType is a package interface, HystrixCommand can not invoke the fallback method, so the hystrix fallback will fail too.
Here is my sample code.
```
interface Github {
	@RequestLine("GET /")
	String get();
}

public class Main2 {
	public static Github fallback = () -> "i am fallback";

	public static void main(String[] args) {
		Github target = HystrixFeign.builder().target(Github.class, "http://api.github.com/ss", fallback);
		System.out.println(target.get());
	}
}
```
And the exception:
```
Caused by: java.lang.IllegalAccessException: Class feign.hystrix.HystrixInvocationHandler$1 can not access a member of class com.lzy.main.p2.Github with modifiers "public abstract"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:490)
	at feign.hystrix.HystrixInvocationHandler$1.getFallback(HystrixInvocationHandler.java:75)
	... 39 common frames omitted
com.netflix.hystrix.exception.HystrixRuntimeException: get timed-out and fallback failed.
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:816)
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:790)
	at rx.internal
```
I try to fix this by using method.setAccessible.But it does not look very graceful.
https://github.com/liuzhengyang/feign/commit/b4fdd67f5567530736686179b1f18790604cb828

**Comment by adriancole** [comment]
interesting. I wonder if we can do this set accessible thing up-front, for
example, in the builder or the contract?

**Comment by caarlos0** [comment]
are the two classes in the same package (Github and Main2)?

**Comment by adriancole** [comment]
Good point. If these classes are in different jars I don't think set
accessible will save you iirc.

**Comment by liuzhengyang** [comment]
@caarlos0，yes. In my example, they are in the same file.

**Comment by liuzhengyang** [comment]
If i rename the package name of HystrixBuilderTest class  from `feign.hystrix` to `feign.hystrixtest`, some test cases will fail.
After i add this code snatch to `HystrixInvocationHandler`. We can passes test cases.
```
if (!method.isAccessible()) {
		      method.setAccessible(true);
 }
```
Full version
```
final class HystrixInvocationHandler implements InvocationHandler {

  private final Target<?> target;
  private final Map<Method, MethodHandler> dispatch;
  private final Object fallback; // Nullable

  HystrixInvocationHandler(Target<?> target, Map<Method, MethodHandler> dispatch, Object fallback) {
    this.target = checkNotNull(target, "target");
    this.dispatch = checkNotNull(dispatch, "dispatch");
    this.fallback = fallback;
  }

  @Override
  public Object invoke(final Object proxy, final Method method, final Object[] args)
      throws Throwable {
    String groupKey = this.target.name();
    String commandKey = method.getName();
    HystrixCommand.Setter setter = HystrixCommand.Setter
        .withGroupKey(HystrixCommandGroupKey.Factory.asKey(groupKey))
        .andCommandKey(HystrixCommandKey.Factory.asKey(commandKey));

    HystrixCommand<Object> hystrixCommand = new HystrixCommand<Object>(setter) {
      @Override
      protected Object run() throws Exception {
        try {
          return HystrixInvocationHandler.this.dispatch.get(method).invoke(args);
        } catch (Exception e) {
          throw e;
        } catch (Throwable t) {
          throw (Error) t;
        }
      }

      @Override
      protected Object getFallback() {
        if (fallback == null) {
          return super.getFallback();
        }
        try {
	      if (!method.isAccessible()) {
		      method.setAccessible(true);
	      }
          Object result = method.invoke(fallback, args);
          if (isReturnsHystrixCommand(method)) {
            return ((HystrixCommand) result).execute();
          } else if (isReturnsObservable(method)) {
            // Create a cold Observable
            return ((Observable) result).toBlocking().first();
          } else if (isReturnsSingle(method)) {
            // Create a cold Observable as a Single
            return ((Single) result).toObservable().toBlocking().first();
          } else {
            return result;
          }
        } catch (IllegalAccessException e) {
          // shouldn't happen as method is public due to being an interface
          throw new AssertionError(e);
        } catch (InvocationTargetException e) {
          // Exceptions on fallback are tossed by Hystrix
          throw new AssertionError(e.getCause());
        }
      }
    };

    if (isReturnsHystrixCommand(method)) {
      return hystrixCommand;
    } else if (isReturnsObservable(method)) {
      // Create a cold Observable
      return hystrixCommand.toObservable();
    } else if (isReturnsSingle(method)) {
      // Create a cold Observable as a Single
      return hystrixCommand.toObservable().toSingle();
    }
    return hystrixCommand.execute();
  }

  private boolean isReturnsHystrixCommand(Method method) {
    return HystrixCommand.class.isAssignableFrom(method.getReturnType());
  }

  private boolean isReturnsObservable(Method method) {
    return Observable.class.isAssignableFrom(method.getReturnType());
  }

  private boolean isReturnsSingle(Method method) {
    return Single.class.isAssignableFrom(method.getReturnType());
  }

  static final class Factory implements InvocationHandlerFactory {

    @Override
    public InvocationHandler create(Target target, Map<Method, MethodHandler> dispatch) {
      return new HystrixInvocationHandler(target, dispatch, null);
    }
  }
}
```

**Comment by rafabene** [comment]
The following code also fails:

```
Greeting fallback = new Greeting() {

            @Override
            public String sayHi() {
                return "Bye";
            }

        };

        Greeting api = HystrixFeign.builder().target(Greeting.class, "http://localhost:80", fallback).sayHi;
```
The exception is **com.netflix.hystrix.exception.HystrixRuntimeException: sayHi timed-out and fallback failed.**

But after debugging, I was able to find the cause as: 

```
HystrixInvocationHandler$1.getFallback() line: 89	- java.lang.IllegalAccessException: Class feign.hystrix.HystrixInvocationHandler$1 can not access a member of class *.ApiGatewayController$Greeting with modifiers "public abstract"
```

**Comment by adriancole** [comment]
My only comment is that the accessibility thing should be done up-front, if
possible ex in the contract or in HystrixFeign.Builder as the reference to
the fallback object doesn't change at runtime. This reduces the amount of
reflection calls, and also makes any errors about setaccessible happen up
front.

anyone for a PR?

**Comment by liuzhengyang** [comment]
I will try this :)
