### ISSUE TITLE
Exception when interface targeted by Feign has default method

### ISSUE THREAD

**Issue by kpavel** [Netflix/feign#392]
According to https://github.com/Netflix/feign#static-and-default-methods , interface targeted by Feign supports static and/or default methods.

Currently when creating such default method, it fails at the validation step: java.lang.IllegalStateException: Method createApp not annotated with HTTP method type (ex. GET, POST)
at feign.Util.checkState(Util.java:117)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:94)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:61)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:137)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:55)
	at feign.Feign$Builder.target(Feign.java:198)
	at feign.Feign$Builder.target(Feign.java:194)
.
.
.

**Comment by adriancole** [comment]
obligatory question.. are you running the latest feign?

**Comment by kpavel** [comment]
Thanks, you are right. I been using relatively old release, 8.14.
Moved to the latest release, 8.16.2 and experience different problem. I'll close this issue and open a new one.
