### ISSUE TITLE
Access exception when interface targeted by Feign has default method

### ISSUE THREAD

**Issue by kpavel** [Netflix/feign#393]
I'm using latest 8.16.2 release. Running example similar to one presented in  https://github.com/Netflix/feign#static-and-default-methods currently fails on the following validation exception:

Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalAccessException: java.lang.invoke.MethodHandle could not access com.play.TestFeign - private access required
	at feign.DefaultMethodHandler.<init>(DefaultMethodHandler.java:36)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:61)
	at feign.Feign$Builder.target(Feign.java:198)
	at feign.Feign$Builder.target(Feign.java:194)
	at com.play.TestFeign.connect(TestFeign.java:37)
	at com.play.Main.main(Main.java:6)
Caused by: java.lang.IllegalAccessException: java.lang.invoke.MethodHandle could not access com.play.TestFeign - private access required
	at java.lang.invoke.MethodHandles$Lookup.checkSpecialAccess(MethodHandles.java:338)
	at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:953)
	at feign.DefaultMethodHandler.<init>(DefaultMethodHandler.java:32)
	... 5 more

While the TestFeign interface:

interface TestFeign {

	@RequestLine("GET /repos/{owner}/{repo}/contributors")
	  List<String> contributors(@Param("owner") String owner, @Param("repo") String repo);

	  @RequestLine("GET /users/{username}/repos?sort={sort}")
	  List<String> repos(@Param("username") String owner, @Param("sort") String sort);

	  default List<String> repos(String owner) {
	    return repos(owner, "full_name");
	  }

	  /**
	   * Lists all contributors for all repos owned by a user.
	   */
	  default List<String> contributors(String user) {
	   	ArrayList<String> contributors = new ArrayList<>();
	    for(String repo : this.repos(user)) {
	      contributors.addAll(this.contributors(user, repo));
	    }
	    return contributors;
	  }

	  static TestFeign connect() {
	    return Feign.builder()
	                .decoder(new GsonDecoder())
	                .target(TestFeign.class, "https://api.github.com");
	  }
}

**Comment by adriancole** [comment]
Can you see if this works when you mark the interface public?

**Comment by kpavel** [comment]
Checked. It doesn't work. Same exception.

**Comment by adriancole** [comment]
k thx

**Comment by adriancole** [comment]
I'm unable to reproduce this. For example, even when feign is in another jar, I can't get this to happen. I've updated the example accordingly. If you can get this example to fail, (ex. by running mvn and target/github crashes) please report back! 

https://github.com/Netflix/feign/commit/74ae7d19b4ad133273e7c730340d8d418d8fd506

**Comment by kpavel** [comment]
Hello Adrian,
After reinstalling Java to the latest one the problem disappeared.
Thanks for your help.

**Comment by adriancole** [comment]
no worries. was good to update the example anyway
